# Generated by Django 4.0.4 on 2022-05-16 01:53

import datetime
from django.db import migrations, models
import django.db.models.deletion
import mainapp.models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='collection',
            name='name_en',
            field=models.CharField(max_length=64, null=True, verbose_name='Наименование'),
        ),
        migrations.AddField(
            model_name='collection',
            name='name_ru',
            field=models.CharField(max_length=64, null=True, verbose_name='Наименование'),
        ),
        migrations.AlterField(
            model_name='cart',
            name='created',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Дата и время создания'),
        ),
        migrations.AlterField(
            model_name='cart',
            name='final_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=9, verbose_name='Итоговая цена'),
        ),
        migrations.AlterField(
            model_name='cart',
            name='owner',
            field=models.GenericIPAddressField(unique=True, verbose_name='IP владельца'),
        ),
        migrations.AlterField(
            model_name='cart',
            name='total_products',
            field=models.PositiveIntegerField(default=0, verbose_name='Общее число товаров в корзине'),
        ),
        migrations.AlterField(
            model_name='cartproduct',
            name='cart',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainapp.cart', verbose_name='Корзина'),
        ),
        migrations.AlterField(
            model_name='cartproduct',
            name='colored_product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cart_products', to='mainapp.coloredproduct', verbose_name='Продукт с цветом'),
        ),
        migrations.AlterField(
            model_name='cartproduct',
            name='subtotal_price',
            field=models.DecimalField(decimal_places=2, max_digits=9, verbose_name='Подытоговая сумма'),
        ),
        migrations.AlterField(
            model_name='collection',
            name='description',
            field=models.TextField(max_length=128, verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='collection',
            name='image',
            field=models.ImageField(upload_to='collection_image/%Y/%m', verbose_name='Изображение коллекции'),
        ),
        migrations.AlterField(
            model_name='collection',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Активно?'),
        ),
        migrations.AlterField(
            model_name='collection',
            name='name',
            field=models.CharField(max_length=64, verbose_name='Наименование'),
        ),
        migrations.AlterField(
            model_name='collection',
            name='pub_date',
            field=models.DateField(default=datetime.datetime.today, verbose_name='Дата публикации'),
        ),
        migrations.AlterField(
            model_name='collection',
            name='slug',
            field=models.SlugField(max_length=64, unique=True, verbose_name='Уникальное обозначение продукта'),
        ),
        migrations.AlterField(
            model_name='collection',
            name='sort_order',
            field=models.PositiveIntegerField(unique=True, verbose_name='Порядок сортировки'),
        ),
        migrations.AlterField(
            model_name='coloredproduct',
            name='color_hex_code',
            field=models.CharField(max_length=6, verbose_name='Hex code цвета товара (после #)'),
        ),
        migrations.AlterField(
            model_name='coloredproduct',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Активно?'),
        ),
        migrations.AlterField(
            model_name='coloredproduct',
            name='name',
            field=models.CharField(max_length=64, verbose_name='Название цвета'),
        ),
        migrations.AlterField(
            model_name='coloredproduct',
            name='old_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, verbose_name='Устаревшая цена'),
        ),
        migrations.AlterField(
            model_name='coloredproduct',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=8, verbose_name='Актуальная цена'),
        ),
        migrations.AlterField(
            model_name='coloredproduct',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='colors', to='mainapp.product', verbose_name='Базовый продукт'),
        ),
        migrations.AlterField(
            model_name='coloredproduct',
            name='pub_date',
            field=models.DateField(default=datetime.datetime.today, verbose_name='Дата публикации'),
        ),
        migrations.AlterField(
            model_name='coloredproduct',
            name='slug',
            field=models.SlugField(max_length=64, verbose_name='Уникальное обозначение продукта'),
        ),
        migrations.AlterField(
            model_name='coloredproduct',
            name='sort_order',
            field=models.PositiveIntegerField(verbose_name='Порядок сортировки'),
        ),
        migrations.AlterField(
            model_name='order',
            name='address',
            field=models.CharField(max_length=1024, verbose_name='Адрес'),
        ),
        migrations.AlterField(
            model_name='order',
            name='first_name',
            field=models.CharField(max_length=128, verbose_name='Имя'),
        ),
        migrations.AlterField(
            model_name='order',
            name='last_name',
            field=models.CharField(max_length=128, verbose_name='Фамилия'),
        ),
        migrations.AlterField(
            model_name='order',
            name='phone',
            field=models.CharField(max_length=20, verbose_name='Телефон'),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('NEW', 'Новый заказ'), ('IN PROGRESS', 'Заказ в обработке'), ('IN PROGRESS', 'Заказ в обработке'), ('IS READY', 'Заказ готов'), ('COMPLETED', 'Заказ выполнен')], default='NEW', max_length=100, verbose_name='Статус заказа'),
        ),
        migrations.AlterField(
            model_name='product',
            name='collection',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='mainapp.collection', verbose_name='Коллекция'),
        ),
        migrations.AlterField(
            model_name='product',
            name='description',
            field=models.TextField(max_length=128, verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='product',
            name='description_en',
            field=models.TextField(max_length=128, null=True, verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='product',
            name='description_ru',
            field=models.TextField(max_length=128, null=True, verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='product',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Активно?'),
        ),
        migrations.AlterField(
            model_name='product',
            name='name',
            field=models.CharField(max_length=64, verbose_name='Наименование'),
        ),
        migrations.AlterField(
            model_name='product',
            name='name_en',
            field=models.CharField(max_length=64, null=True, verbose_name='Наименование'),
        ),
        migrations.AlterField(
            model_name='product',
            name='name_ru',
            field=models.CharField(max_length=64, null=True, verbose_name='Наименование'),
        ),
        migrations.AlterField(
            model_name='product',
            name='pub_date',
            field=models.DateField(default=datetime.datetime.today, verbose_name='Дата публикации'),
        ),
        migrations.AlterField(
            model_name='product',
            name='sizes',
            field=models.ManyToManyField(default=mainapp.models.Product.allSizes, to='mainapp.size', verbose_name='Размеры'),
        ),
        migrations.AlterField(
            model_name='product',
            name='slug',
            field=models.SlugField(max_length=64, unique=True, verbose_name='Уникальное обозначение продукта'),
        ),
        migrations.AlterField(
            model_name='productimage',
            name='description',
            field=models.CharField(max_length=190, unique=True, verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='productimage',
            name='image',
            field=models.ImageField(upload_to='product_images/%Y/%m', verbose_name='Изображение продукта'),
        ),
        migrations.AlterField(
            model_name='productimage',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Активно?'),
        ),
        migrations.AlterField(
            model_name='productimage',
            name='pub_date',
            field=models.DateField(default=datetime.datetime.today, verbose_name='Дата публикации'),
        ),
        migrations.AlterField(
            model_name='productimage',
            name='sort_order',
            field=models.PositiveIntegerField(verbose_name='Порядок сортировки'),
        ),
        migrations.AlterField(
            model_name='promocode',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Активно?'),
        ),
        migrations.AlterField(
            model_name='promocode',
            name='promocode',
            field=models.CharField(max_length=16, unique=True, verbose_name='Промокод'),
        ),
        migrations.AlterField(
            model_name='promocode',
            name='pub_date',
            field=models.DateField(default=datetime.datetime.today, verbose_name='Дата публикации'),
        ),
        migrations.AlterField(
            model_name='promocode',
            name='sort_order',
            field=models.PositiveIntegerField(unique=True, verbose_name='Порядок сортировки'),
        ),
        migrations.AlterField(
            model_name='size',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Активно?'),
        ),
        migrations.AlterField(
            model_name='size',
            name='pub_date',
            field=models.DateField(default=datetime.datetime.today, verbose_name='Дата публикации'),
        ),
        migrations.AlterField(
            model_name='size',
            name='size',
            field=models.CharField(max_length=64, unique=True, verbose_name='Размер'),
        ),
        migrations.AlterField(
            model_name='size',
            name='sort_order',
            field=models.PositiveIntegerField(unique=True, verbose_name='Порядок сортировки'),
        ),
    ]
