# Generated by Django 4.0.4 on 2022-05-16 01:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0002_collection_name_en_collection_name_ru_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='collection',
            name='description_en',
            field=models.TextField(max_length=128, null=True, verbose_name='Описание'),
        ),
        migrations.AddField(
            model_name='collection',
            name='description_ru',
            field=models.TextField(max_length=128, null=True, verbose_name='Описание'),
        ),
    ]
