# Generated by Django 4.0.4 on 2022-05-16 02:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0003_collection_description_en_collection_description_ru'),
    ]

    operations = [
        migrations.AddField(
            model_name='coloredproduct',
            name='name_en',
            field=models.CharField(max_length=64, null=True, verbose_name='Название цвета'),
        ),
        migrations.AddField(
            model_name='coloredproduct',
            name='name_ru',
            field=models.CharField(max_length=64, null=True, verbose_name='Название цвета'),
        ),
    ]
