# Generated by Django 4.0.4 on 2022-09-02 23:00

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0007_alter_cartproduct_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Banner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активно?')),
                ('pub_date', models.DateField(default=datetime.datetime.today, verbose_name='Дата публикации')),
                ('sort_order', models.PositiveIntegerField(unique=True, verbose_name='Порядок сортировки')),
                ('header', models.TextField(max_length=128, verbose_name='Заголовок')),
                ('header_ru', models.TextField(max_length=128, null=True, verbose_name='Заголовок')),
                ('header_en', models.TextField(max_length=128, null=True, verbose_name='Заголовок')),
                ('description', models.TextField(max_length=128, verbose_name='Описание')),
                ('description_ru', models.TextField(max_length=128, null=True, verbose_name='Описание')),
                ('description_en', models.TextField(max_length=128, null=True, verbose_name='Описание')),
                ('link', models.TextField(max_length=256, verbose_name='Ссылка')),
                ('image', models.ImageField(upload_to='banner_image/%Y/%m', verbose_name='Изображение баннера')),
            ],
            options={
                'verbose_name': 'Баннер',
                'verbose_name_plural': 'Баннеры',
            },
        ),
        migrations.AlterField(
            model_name='product',
            name='collection',
            field=models.ManyToManyField(related_name='products', to='mainapp.collection', verbose_name='Коллекции'),
        ),
    ]
